# Generated by Django 2.2.8 on 2020-01-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='GBP Order Total')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customerNumber', models.CharField(blank=True, max_length=250)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=250)),
                ('postCode', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('phone', models.IntegerField(blank=True, default=0)),
                ('shippingName', models.CharField(blank=True, max_length=250)),
                ('shippingAddress', models.CharField(blank=True, max_length=250)),
                ('shippingCity', models.CharField(blank=True, max_length=250)),
                ('shippingPostcode', models.CharField(blank=True, max_length=10)),
                ('shippingCountry', models.CharField(blank=True, max_length=200)),
                ('deliveryPhone', models.IntegerField(blank=True, default=0)),
                ('deliveryMonday', models.BooleanField(default=False)),
                ('deliveryTuesday', models.BooleanField(default=False)),
                ('deliveryWednesday', models.BooleanField(default=False)),
                ('deliveryThursday', models.BooleanField(default=False)),
                ('deliveryFriday', models.BooleanField(default=False)),
                ('deliverySaturday', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('completed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
            ],
            options={
                'db_table': 'Order',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True)),
                ('product', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='GBP Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
    ]
